version: '2'
services:
  web:
    image: dev
    user: "900:900"
    ports:
    - "3000"
    environment:
      RUN_ENV: "development"
      EXTERNAL_IP: "192.168.2.100"
    volumes:
    - "/vagrant/dockers/srv-barcode-1s/test/config:/app/config"
    depends_on:
    - redis
  redis:
    image: "docker-registry.dsk2.picompany.ru/redis:3.0.7"
    user: "900:900"
    ports:
      - "6379"
    environment:
      RUN_ENV: "development"
    volumes:
      - "/vagrant/dockers/srv-barcode-1s/test/redis:/var/redis"
      - "/vagrant/dockers/srv-barcode-1s/test/redis/config:/opt/redis/config"
