version: '2'
services:
  web:
    image: "docker-registry.dsk2.picompany.ru/srv-barcode-mobile:0.3.0"
    ports:
    - "3000"
    environment:
      RUN_ENV: "development"
      EXTERNAL_IP: "192.168.243.122"
      USER_ID: 501
      GROUP_ID: 501
    volumes:
    - "/Users/misha/projects/dockers/srv-barcode-mobile/tmp:/app/config"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
