consul_server:
  image: "consul:0.6.3"
  user: "900:900"
  net: "host"
  ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    - "8600:8600/udp"
  environment:
    RUN_MODE_SERVER: "True"
    DATACENTER: "dsk3"
    EXTERNAL_IP: "192.168.2.89"
    TOKEN: "tZUvxcMR7sjHbhAhO5HM3g=="
    UI_ENABLE: "True"
  volumes:
    - "/home/vagrant/consul/data:/var/opt/consul"
    - "/home/vagrant/consul/config:/opt/consul/config"
  command: "consul agent -config-dir /opt/consul/config -bootstrap-expect 3"
