---
- name: Download
  get_url:
    url: "{{ dist_url }}"
    dest: "/tmp/{{ dist_filename }}"
    checksum: "{{ dist_checksum }}"
    validate_certs: no

- name: Extract
  unarchive: src=/tmp/{{ dist_filename }} dest=/opt copy=no

- name: Move
  shell: "mv /opt/jruby-{{ dist_version }} {{ srv_home }} && rm /tmp/{{ dist_filename }}* chdir=/tmp"
